### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RoblokazPlays**
wiki go brrrr

### CODE REVIEW

**Comment by Iyxan23** [comment]
Doesn't look like a wiki, looks like a readme update :hidepain:

**Comment by RoblokazPlays** [comment]
bruh why didn't it add the wiki :hidepain:

**Comment by Iyxan23** [comment]
I'll merge it, the old sentence is a bit weird

**Comment by ToastcodeDev** [comment]
-__- **Add Wiki brr**

**Pull request merged**
